name: cron

permissions:
  contents: write

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - run: bun i
      - run: bun run build
      - run: bun run start
      - name: Commit report
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Updated Data: `date +'%Y-%m-%d %H:%M:%S'`"
          git push
